### ISSUE TITLE
Usage instructions suggest wrong placement of -h parameter

### ISSUE THREAD

**Issue by kloesing** [robgjansen/onionperf#13]
This is a very minor issue, but it might confuse new users.

The usage instructions say:

```
usage: onionperf [-h] {monitor,measure,analyze,visualize} ...
```

But the correct syntax would be:

```
usage: onionperf {monitor,measure,analyze,visualize} [-h] ...
```

Further down below the usage instructions (correctly) say:

```
Use 'onionperf <subcommand> --help' for more info
```

Maybe there's an easy fix?

**Comment by robgjansen** [comment]
I think you are referring to the output that appears if you just run onionperf without any arguments. Is that right?

Both of these are technically correct invocations:

```
onionperf [-h] {monitor,measure,analyze,visualize} ...
onionperf {monitor,measure,analyze,visualize} [-h] ...
```

The help menu you get from the first invocation is general purpose application help and provides some information for each possible subcommand, and the help menu you get from the second invocation is dependent on which command you entered and will give you command specific help.

This could really be written as

```
onionperf [-h] {monitor,measure,analyze,visualize} [-h] ...
```

(although the first -h flag here overrides the second)

All of this is the default output generated by using the python `argparse` library, so I'm not sure if it should be changed. I could take off the top level help, but I think its useful.

**Comment by kloesing** [comment]
Oh, I see.  You're right, both are useful and should be kept.  Sorry for the noise, I'll close this ticket.
