### ISSUE TITLE
Add new config option to specify public IP address

### ISSUE THREAD

**Issue by kloesing** [robgjansen/onionperf#14]
I'm running OnionPerf on an EC2 instance with this ifconfig output:

```
eth0      Link encap:Ethernet  HWaddr 0e:72:3c:bd:26:a1  
          inet addr:172.16.0.86  Bcast:172.16.0.255  Mask:255.255.255.0
          inet6 addr: fe80::c72:3cff:febd:26a1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:661816 errors:0 dropped:0 overruns:0 frame:0
          TX packets:476454 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:363109016 (363.1 MB)  TX bytes:113909581 (113.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:164714 errors:0 dropped:0 overruns:0 frame:0
          TX packets:164714 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:31426744 (31.4 MB)  TX bytes:31426744 (31.4 MB)
```

But the public IP address is 54.165.x.x.  Would it be possible to add a config option for the IP address that overrides whatever OnionPerf guesses as the server's IP address?

**Comment by robgjansen** [comment]
Should be easy to add.

Just for reference, the way that onionperf guesses the IP address now is it connects to 8.8.8.8 and looks for the destination address in the reply packet. This is done in `util.get_ip_address()`:

https://github.com/robgjansen/onionperf/blob/f8bef512d3b8cff4ca544ee39155c5193a2d0ae7/onionperf/util.py#L99

**Comment by kloesing** [comment]
Hmm, that code also fails to provide the publicly routable IP address of my laptop which is, of course, behind a NAT device.  But I might want to run Torperf on this laptop anyway with forwarding rules defined in the NAT box.  So, I think having a config option to override that mechanism of finding out the IP address would be quite useful.

Some quick remarks on the code while I'm looking at it:
- Why port 80?  Don't you want port 53 there?
- Can you close that socket before returning?

**Comment by robgjansen** [comment]
I added a new option for this, called `--tgen-connect-ip` in 38b401e242f87396c79ab9fb7632101184c404a3. I have not yet tested it, so let me know if you find that it seems to work and I'll close the issue.

**Comment by kloesing** [comment]
It doesn't quite work yet.  I got the following line in my `tgen.graphml.xml`:

```
      <data key="d2">&lt;_sre.SRE_Match object at 0x7efc4ad989f0&gt;:80</data>
```

I think the reason is that `re.match()` returns a `MatchObject`, not a string.  The fix seems to be to return `ip.group(0)` rather than just `ip`.  When I change that locally it seems to work fine.  Not sure if it has any side effects I'm not seeing.

**Comment by robgjansen** [comment]
Sorry about that! I think we can close the ticket now after 8030375394eaac1848a244f269000c2c2518e858, right?

**Comment by kloesing** [comment]
Sure.  Thanks!  Will close.
