### ISSUE TITLE
Make the default model more similar to actual Torperf behavior

### ISSUE THREAD

**Issue by kloesing** [robgjansen/onionperf#16]
I noticed that the default model in OnionPerf is slightly different than Torperf's.  Torperf makes requests as follows:
- *:00 50 KiB
- *:02 1 MiB
- *:05 50 KiB
- *:08 5 MiB
- *:10 50 KiB
- *:15 50 KiB
- *:20 50 KiB
- *:25 50 KiB
- *:30 50 KiB
- *:32 1 MiB
- *:35 50 KiB
- *:40 50 KiB
- *:45 50 KiB
- *:50 50 KiB
- *:55 50 KiB

But OnionPerf picks one of the three downloads at random every 5 minutes.  That means it's downloading 5 MiB much more often than Torperf.  In absolute numbers:

```
ip-172-16-0-86-1048576-2016-03-08.tpf:38
ip-172-16-0-86-51200-2016-03-08.tpf:31
ip-172-16-0-86-5242880-2016-03-08.tpf:26
```

As an easy fix, how about we change the weights in OnionPerf's model as follows?

```
        g.add_edge("pause", "transfer50k", weight="12.0")
        g.add_edge("pause", "transfer1m", weight="2.0")
        g.add_edge("pause", "transfer5m", weight="1.0")
```

That's not exactly Torperf's model but hopefully a good-enough approximation.

An alternative would be to make three disconnected graphs, each of which having its own start node, an initial pause node, a transfer node, and a pause-between-requests node.  But I guess TGen doesn't support multiple tokens in a graph, right?

**Comment by robgjansen** [comment]
Your suggestion to set the weights seems great, and a perfect use of the `weights` attribute.
